EXTRAMODULES=$(find /usr/lib/modules -type d -iname 6.1.51*xanmod* | rev | cut -d "/" -f1 | rev)

post_install() {
  depmod $(find /usr/lib/modules -type d -iname 6.1.51*xanmod* | rev | cut -d "/" -f1 | rev)
}

post_upgrade() {
  depmod $(find /usr/lib/modules -type d -iname 6.1.51*xanmod* | rev | cut -d "/" -f1 | rev)
}

post_remove() {
  depmod $(find /usr/lib/modules -type d -iname 6.1.51*xanmod* | rev | cut -d "/" -f1 | rev)
}
